server:
  port: 9092

spring:
  datasource:
    name: huaxiaoyu
    url: jdbc:mysql://localhost:3306/huaxiaoyu?serverTimezone=Asia/Shanghai
    username: ${env.DB_USERNAME}
    password: ${env.DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启控制台 SQL 日志打印
    map-underscore-to-camel-case: false # 驼峰和下划线互转

file:
  ip: localhost:9092
